import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import ThemeToggle from "./ThemeToggle";
import FloatingDecor from "./FloatingDecor";
import SoundToggle from "./SoundToggle";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased`}
      >
        {children}
        {/* App footer */}
        <footer className="fixed bottom-0 left-0 right-0 text-xs opacity-90 px-4 py-2 bg-white/70 dark:bg-black/40 backdrop-blur-sm border-t flex items-center justify-center">
          This project was made for a technical exam by Rene Salvacion at Umbra Digital Company.
        </footer>
        {/* Theme toggle fixed at bottom-right */}
        <ThemeToggle />
        {/* Background moving pens and paper */}
        <div className="paper-layer" />
        <FloatingDecor />
        {/* Ambient theme sound toggle */}
        <SoundToggle />
      </body>
    </html>
  );
}
